### ISSUE TITLE
I don't understand the concept

### ISSUE THREAD

**Issue by Marsad1998** [durable-workflow/sample-app#2]
I have read the official documentation and now came across this sample-app I have seen the workflow files app/Workflow folder. But there is not much of sample available like where need to start workflow. How we can schedule jobs and handle the process etc.

**Comment by rmcdaniel** [comment]
To start the workflow you can use the artisan command at  app/Console/Commands/Workflow.php

**Comment by Marsad1998** [comment]
thank you for your reply. But problem is Do i need to create Rule and Criteria Table separately to automate these process? Because I want to achieve something like this. https://www.youtube.com/watch?v=EAMz_xzxkGk

I have do the steps written in docs as I'm new to this would you share any link with formal tutorial link where it has step by step guide of what blade files do i need to make, controllers, and how workflow is automated. ? Any help in this regard much much appreciated.

**Comment by rmcdaniel** [comment]
I have written some blog posts here https://medium.com/@rlmc that might help. The email verfication blog post shows some routing and blade stuff.

**Comment by WPWebSEO** [comment]
Thanks Man! Articles help alot but I still have question. Is this package suitable to build workflow automation like in the Zoho CRM? If yes then how will we pass the actions and triggers from blade->controller->this package ? I may sound naïve but any help or hint in this regard much much appreciated.

**Comment by Marsad1998** [comment]
Thanks Man! Articles help a lot but I still have question. Is this package suitable to build workflow automation like in the Zoho CRM? If yes then how will we pass the actions and triggers from blade->controller->this package ? I may sound naïve but any help or hint in this regard much much appreciated.

**Comment by rmcdaniel** [comment]
Yes, it can be used to create workflow automation similar to systems like Zoho CRM. However, implementing a complete system like Zoho CRM involves more than just the workflow; you'll also need user interfaces, storage mechanisms, and integration with other services.

Here's a high-level overview of how you can use Laravel Workflow to implement action-trigger based automations:

Define Triggers and Actions: You'll first need to define what triggers (events) can start a workflow and what actions (activities) can be performed as a result.

Blade View (UI): This is where you create a user interface for your CRM. Through this UI, users will define when a trigger should start a workflow and what actions should be taken.

Use form elements (like dropdowns) to let users select triggers and actions.
When users configure their workflow and hit 'Save', send this configuration to a Laravel controller using standard form submission or AJAX.

Laravel Controller: This receives the trigger and action configuration from the Blade view.

Parse the received data to determine which trigger and action were selected.
You can then initiate the workflow based on the selected trigger.
Use Laravel Workflow:

Define your workflows in the Laravel Workflow package. As per the documentation you provided, a workflow can be a class where you define which activities (actions) are to be performed.
Create separate activity classes for each possible action (like sending an email, updating a record, etc.).
Based on the trigger from the Blade view, you can start the specific workflow using WorkflowStub::make(YourWorkflow::class) and then run it.
Integration with Events: If you want real-time automation (like "when a new user registers, send them an email"), you might want to integrate Laravel's event system. When an event happens in your application (like a new user registration), you can fire a Laravel event. This event can then initiate the corresponding workflow.

Passing Data: Data can be passed from the Blade view to the controller using standard form inputs. From the controller, you can pass this data directly to your workflow and activities.

Here's a simple, illustrative example:

```html
<form action="/create-workflow" method="POST">
   <select name="trigger">
      <option value="new_user">New User Registration</option>
      <!-- Other triggers -->
   </select>

   <select name="action">
      <option value="send_email">Send Welcome Email</option>
      <!-- Other actions -->
   </select>

   <input type="submit" value="Save">
</form>
```

```php
public function createWorkflow(Request $request) {
   $trigger = $request->input('trigger');
   $action = $request->input('action');

   // Based on the trigger, initiate the workflow
   if ($trigger == "new_user") {
      $workflow = WorkflowStub::make(NewUserWorkflow::class);
      $workflow->start($action); // Passing action as a parameter to the workflow
   }
}
```

This is a very high-level overview, and the real implementation will require careful planning, especially when defining how actions, triggers, and workflows interact.
